### ISSUE TITLE
Write function: tweet -> sentiment [-1, 1] with -1 neg; +1 positive

### ISSUE THREAD

**Issue by rgeirhos** [rgeirhos/data-science#9]

**Comment by huyenle812** [comment]
`from textblob import TextBlob
def get_tweet_sentiment(cleaned_tweet_tokens): #list of cleaned tokens from a tweet
    clean_tweet = ' '.join(cleaned_tweet_tokens)
    return TextBlob(clean_tweet).sentiment.polarity`
